language: node_js
node_js:
  - '6'
install:
  - yarn install
after_success:
  - yarn coverage
  - ./typedoc.sh
env:
  global:
    secure: ffinL6ccbMKlWkN7wyiypVOtwDz9Zw4Hllr3RWwrJpKpAfcQDJ2u5h52C4atJxjCStZnzcYzJ/JZcqZBZ2EDVucDhiAOcLkCrKwzTR5jXzVSJ6lonYZulxkSjxbNHwLqU4kdkmlUR/271C6S0lvWtd0sc0iHJq9Ow5cO6K8ZEUC/G3WpOxFYQ8icvVPkPV3KXdRV9J+5y0xJQGwfjV3gt01qAvrKzmvHVm36TYy0WxFA+Vm5ov8eGI3w/LxlVSL5oOfvA4ky2brIZYNsQuicODLroxzGeGP9wKJ797rD2lWzO2jM1pKmGlTvzfOIqlhE8BYEne+r7J21csOyg5GTTuMcFP8J1pNuTi2Z+iPdW7DnPb6dT7uObJ094TgZ1NWYtaSms5bUj/SCF4wHRxaLyq2+DkT5i445lpeHg+1FpGd4dJpBQckA31Cd+rVafhqkUW974Iych9I3CWAKREXKOYwMQRmeRkS9Zw+b+xuhjQnBYzQ0XA5jXiNkV3ybG/zw0pkKEHJHKw0RLkuRFqmsmlb0sWAWPtLvSkrzY9wU52JaG649Qc9lpzAevAfh5LREFjt+9bFqtdgRfgMPgqnbM1n41KUsN5E8Y+zQPsggBhEP2bAbViEqJtjK2ih0jDEzy9lQQsvuXEMPwPIHI8vVTePG8b6uVze3eS5J2cs7x1E=
